image: johnjz/comp2300-ci:2019-latest

build-check:
  tags:
    - comp2300
  script:
    - mv /pio-proj-template/.pioenvs .
    - pio run --disable-auto-clean

pledge-of-integrity:
  tags:
    - comp2300
  script:
    - python3 /validate.py --schema https://cs.anu.edu.au/courses/comp2300/assets/schemas/pledge-of-integrity.json ./pledge-of-integrity.yml
